name: CI for PR

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "18.x"
    - run: yarn
    - run: yarn run lint
    - run: yarn run build
